[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "llamaindex-experiments"
version = "0.0.0"
description = "LlamaIndex experiments"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
  "pyyaml",
  "python-dotenv",
  "tqdm",
  "setuptools",
  "pymilvus",
  "redis",
  "pymongo",
  "neo4j",
  "llama-index",
  "llama-index-core",
  "llama-index-llms-ollama",
  "llama-index-llms-openai-like",
  "llama-index-embeddings-ollama",
  "llama-index-embeddings-langchain",
  "llama-index-vector-stores-milvus",
  "llama-index-graph-stores-neo4j",
  "llama-index-readers-file",
  "llama-index-readers-json",
  "llama-index-readers-mongodb",
  "llama-index-readers-database",
  "llama-index-readers-milvus",
  "llama-index-readers-obsidian",
  "llama-index-readers-whisper",
  "llama-index-readers-graphdb-cypher",
  "llama-index-storage-index-store-redis",
  "llama-index-storage-docstore-mongodb",
  "llama-index-storage-kvstore-redis",
  "llama-index-tools-database",
  "llama-index-tools-neo4j",
  "llama-index-multi-modal-llms-ollama",
  "llama-index-packs-neo4j-query-engine",
  "llama-index-experimental",
  "torch",
  "torchvision",
  "torchaudio",
  "transformers",
  "sentence-transformers",
  "ragas",
  "datasets",
  "huggingface-hub",
  "pandas",
  "numpy",
  "matplotlib",
  "seaborn",
  "pytest",
  "evaluate",
  "rouge-score",
  "bert-score",
  "tiktoken",
  "nest-asyncio",
  "accelerate",
  "pytest-asyncio",
  "pymupdf",
  "pymupdf4llm",
  "spacy",
  "nltk",
]

[tool.setuptools]
package-dir = {"" = "src"}
[tool.setuptools.packages.find]
where = ["src"]